travis:
  secure:
    BINSTAR_TOKEN: KJdZt98QT48JhpU0Hb2QziXJ8HR3upVSUxA5LrhJtP8oEtdDwkzRHQ2mXfM93U983pgNoDTKcojHT46aQgjvT+ZdOwGOaPqyV6tuUfJ1UPzdAPBW1v8fs5ODsB1WrdOEyXBr8PChu+bWG70J5/0KxLPwZNKC780bvtTyyGVzb8FLLxKGQkBx6S6mDYmtLlilFMwUqLlJyUQqfpVax2qcLCgHDagmENDlTvdW1ZZsRuRylG6J9hh3ZeUeEmI4wkvBB38qsqA1fsS0mCE6w4WLMHAhrEig+ogLtw/I90aq3FRMEB+QU829G8yL9PIJIwX7t7fp6FsMqJDJgithv/I0bq49Pml75ShKcbBGZK12bl86Sx/MqR5ni+2Zwyj4gVx9zWSz6SmWh1Z8KZ8ck2cXHUexFS6koz2ybm6IlcspKbHL+qGyqYw9dYhvgSrvC5qKeS3dby2Tvka8uN8Zb9q6mhS8O2AfkSWk6R3DOFSmAN9lWszjG18ziRz+nTvPuMb/Bm14KtNKLcEZnlVghsUT0hNw9boqX6kSxGyzYaBhnvnKdovZYhyL743ingVcXnokMxibqVp1vBlz95lFTlRryrkid1rB4zIjFATaKyLtFHR73L/mAQ90uPYd/D5+JlqkscQ9/ssG1QtuS8S+gYNQ0nVZsUJzqg8u8nbgadAMhj8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
