travis:
  secure:
    BINSTAR_TOKEN: gk16JzqiKiFqaBhDU80KVW3DZajbTlVA1Ao4oMsEPxnCXTl4RRBCgpJkekoEgwFnmFSB0wNTsWhORo3KjgwKqT+OyTNTkPI5zz8ezQ0QVnMYqqXI1RRNGCzfMfrLX6OlsqETyDANqUa9E4cC2xm8peabk60FZgwZISLPff2CNmCEO9mESJe7JxsWSDs+J7TGKuuJFwM8arTUwJJyXyoE1IEoIOuzCoF8uuR9pjCpG6RQo7fTgXFb6Rg5eW7o+TewmzSbGMqCUzrTRftugXefviIDuSc4GrLyDuwx/1h/BOpqeSWuBuaZ1eN3hb2ey1EbPMILchBOCjCzW5qkcUEfVahGD9ESEV8XV+F2CkXKopWNE2VOSL4Uvylc8nADT/WZ8d7UIy5EZjkw0o6pf4Mfm/3h7Ybx/9iiWZeH1U6/eFS+3ATGkPkZqdbiSdgsn8gSqAF05gSSTk7KBTC4TTGOxr7f+onXMUcj5unhwDmHOO2fa9APnRvLA644MIIjYcnoZUta+AYAqJWSmlICsPSIkqBqoUOfD6aABWPoPmIuCHHw2QaCyBGqGxj1twmtH4ivphkGs1r5jCGhhpwZAUGa1gkVhRZplr4m04vYU1RfxHZtk2eNNcwl776KWqznl1gDEq/hChwhL1TeDdw628Uf55jOIzSvW8ADmW+jjEP8c3c=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
