travis:
  secure:
    BINSTAR_TOKEN: evz6a/7kTseTw0rhp46zbhszZjOdnp7hMo1F88Y7BOebq+JrmQqW6PISkb2CB4vZrKyU/QV9is4t/47kg7xNYRq9+UYkPCnsoXuAoSHmQhaSmAUvSt0Du5MgxpHXPbvTfyvw4V0+gMYEm8FKUxlR8TMCuFt8eLTEBzQhixxORMXO2tJGr8bDIkYjJxHiM1Lc73aor6ZDNA3IRnbmy1FC48spNUumKoFmxVvDVZPvr5NctXqFT6LuRJJFTWgC2run1DybGOivdOOL71oKmDWKO1z7yNYtTX1CUuk7ILhQsC/xEzF7jgZeLiZWKU67gkQRugCztOKJDSfUkmBLAerVnrY5+Rxyp4BKKX7nFw6yLYPzuzaeUAFzv8ImxrSbmTxHLcOFYa2b4/eoMPqBWwm0WgSiyhVzFtrtAtUUt3U4rma8JeLNDuTXbbR/SU/5TToVBgmM2kasP2OvfYDeC6vjzUv0/TdLPZZIILG7adLCr7DwWH6VcEw6EQtPpVo13yugAUmhfs85eQBcOd19YqvMDHlpMmE0UgkDcii5V7HjDXRYD8RD3tlWE8wlaDV+SfCvF3x8QSvkPVPlWDVvot/JFqJJS4kjKXMKNH16uZaYPM/GMztY+jUlp3VCqryG9RsPTRTQdU+ERaxU00vr3UC9jmeAyfOnoWMY1bFQycO4JG0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
