travis:
  secure:
    BINSTAR_TOKEN: B4Qxzlyi2BkOWdM88mII+Kt8xWCOlYgyCwaFQSxiJCfOK31UpHQqYOwok1s3VQkP8wi3/5uGgAGnDH+QX+APl9YR9B+TkDtvygJ7J9aEhrOgdsVoIBrQtxN1ikDlVZ16/pZrMhVRT6senP0L6Oz8TPBzjXC89VzvLnmNHDkbv3Bb/QT7COZmOOQGhaQ65kC0YBuGqklYiAn8bhLKwHK6Z1Z1ajqERefom8fTs18irRdLCttBf2A3slXzxgA3Am8IaNeY1uIDv94Z7U56mcekNP6tGIPyik2irVhRwLTkKN2WVlinOrgcmF3/MbHE6eecrs6UCSsab9iM4mJP0axhqxC+uUw5LSnAfekRgUOEyzT/x1+W3Sifpz2qShnH8pmQlz1IhvaeFp5gLTEscwD3Dp5Rz/Bb3T7yPnttBg3DSVm23w+9OaTn2oDOniR1/cE/tlZ1VNvPjWfo0c5rVAD9arnEagWn1aH3u33pcBN8he+dMmt9Wp99pBrNtcHlRJ6o9I/HCkdV6FX1EiaI+z1mmTr1hYZMEJejIPRTsQ6QzjA6wiRlchdH5K8XLDw2ioJrvK+sB0hxmzWDQ1SQTizwTm3KWsV1Xd6cbSCw699J8wxLTx2qSiDtcij8wD8I5LV6khvdDkHffVcjyP4+wnli+Evt7t+W+zvGeb7iSKhux+s=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
